server:
  port: 8920
  maxSize: 20
spring:
  application:
    name: kiss-nest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Helloshic7!
    url: jdbc:mysql://rm-j6ca5pt36q4h487712o.mysql.rds.aliyuncs.com/kiss-backhub?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.kiss.kissnest.mapper: debug
jenkins:
  url: http://build.kisscloud.io
#  account: admin
#  password: e20e6ba9448f468fb39dec3529984cfc
  buildUrl: http://build.kisscloud.io/job/%s/build
  buildWithParameterUrl: http://build.kisscloud.io/job/%s/buildWithParameters
  generateTokenUrl: http://build.kisscloud.io/user/%s/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken
  buildLogUrl: http://build.kisscloud.io/job/%s/%s
  buildOutputPath: /logText/progressiveHtml
  crumbPath: /crumbIssuer/api/json
  bin:
    ip: 192.168.0.192
code:
  bin:
    ip: 10.100.100.185

kiss:
  nest:
    clientId: e489c5a6da934fe2b441824809b50ae6
    clientSecret: b1c1f5f3d6cb43a2a0b599daaa99b558
    clientExpired: 1296000
    webHook:
      url: http://localhost:8920/kiss/nest/note

gitlab:
  server:
    url: http://git.kisscloud.io
    token:
      path: /oauth/token

build:
  log:
    maxSize: 20
#http://localhost:8080/jenkins/job/guyue/43/
feign:
  httpclient:
    connection-timeout: 60000
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
