server:
  port: 8920
spring:
  application:
    name: kiss-nest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Helloshic7!
    url: jdbc:mysql://rm-j6ca5pt36q4h487712o.mysql.rds.aliyuncs.com/kiss-backhub?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  config-location: classpath:mybatis-config.xml
logging:
  level:
    com.kiss.kissnest.mapper: debug
jenkins:
  url: http://localhost:8060
#  account: admin
#  password: e20e6ba9448f468fb39dec3529984cfc
  buildUrl: http://localhost:8060/job/%s/build
  buildWithParameterUrl: http://localhost:8060/job/%s/buildWithParameters
  generateTokenUrl: http://localhost:8060/user/%s/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken

kiss:
  nest:
    clientId: e489c5a6da934fe2b441824809b50ae6
    clientSecret: b1c1f5f3d6cb43a2a0b599daaa99b558
    clientExpired: 1296000

gitlab:
  server:
    url: https://gitlab.com
    token:
      path: /oauth/token